### ISSUE TITLE
Issues with `JULIA_PROJ` on Linux

### ISSUE THREAD

**Issue by edwardlavender** [edwardlavender/patter#46]
On `siam-linux20`, if `JULIA_PROJ` is set, `julia_connect()` fails with:

```
Error: Error happens in Julia.
InitError: could not load library "/home/EAWAG/lavended/.julia/artifacts/4a6fe8c6eda7f19d80afb858eb9f7cbe312f1453/lib/libnetcdf.so"
libhdf5_hl.so.310: cannot open shared object file: No such file or directory
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
@ Base.Libc.Libdl ./libdl.jl:120
[2] dlopen(s::String, flags::UInt32)
@ Base.Libc.Libdl ./libdl.jl:119
[3] macro expansion
@ ~/.julia/packages/JLLWrappers/GfYNv/src/products/library_generators.jl:63 [inlined]
[4] __init__()
@ NetCDF_jll ~/.julia/packages/NetCDF_jll/BCx4u/src/wrappers/x86_64-linux-gnu.jl:17
[5] run_module_init(mod::Module, i::Int64)
@ Base ./loading.jl:1378
[6] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
@ Base ./loading.jl:1366
[7] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any}, ignore_native::Nothing; register::Bool)
@ Base ./loading.jl:125
```

This happens on RStudio Server, even if `R` is run from the Terminal after having unset `LD_LIBRARY_PATH`. 

If `JULIA_PROJ` is not set, `julia_connect()` works. 

I haven't tested whether this is an issue on other `Linux` machines/distributions. 

```
> sessionInfo()
R version 4.4.2 (2024-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Debian GNU/Linux 11 (bullseye)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Zurich
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.2    tools_4.4.2       rstudioapi_0.17.1
```

The workaround for now on Linux is to avoid setting `JULIA_PROJ`.

**Comment by edwardlavender** [comment]
On `siam-linux20`, setting `JULIA_PROJ = here::here(".")` in the `wahoo-flapper` project now works (`R` 4.5.0). (The `SuiteSparse_config_malloc_func_set` error can be safely ignored.)

<details>
<summary>Session info</summary>

```r
> sessionInfo()
R version 4.5.0 (2025-04-11)
Platform: x86_64-pc-linux-gnu
Running under: Debian GNU/Linux 11 (bullseye)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Zurich
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.25 compiler_4.5.0      here_1.0.1          rprojroot_2.0.4     parallel_4.5.0      tools_4.5.0        
[7] rstudioapi_0.17.1   yaml_2.3.10         renv_1.1.4 
```

</details>

<details>
<summary>`Julia` Project.toml</summary>

```toml
[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeoArrays = "2fb1d81b-e6a0-5fc5-82e6-8e06903437ab"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Patter = "faabfbac-af09-47ee-bc95-5e336c516b5a"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Wahoo = "34ee53bd-d3f2-451a-8e30-9c0767249144"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"
```

</details>

<details>
<summary>`Julia` connect</summary>

```r
> library(patter)
This is {patter} v.2.0.1. For an overview, see `?patter`. For support, raise an issue at https://github.com/edwardlavender/patter/issues. WARNING: On Linux, {patter} can be used but you cannot simultaneously use geospatial routines in `R` and `Julia`. Thus, you can only call `library(terra)` or `terra::foo()` and use {patter} routines that exploit {terra} and other geospatial packages in `R` sessions that are not connected to a `Julia` session (via `julia_connect()`). Set the map in `Julia` using a file path (via `set_map()`). Check the {patter} function documentation for supported options.
> julia_connect()
`patter::julia_connect()` called @ 2025-06-08 12:43:40... 
... Running `Julia` setup via `JuliaCall::julia_setup()`... 
Julia version 1.11.2 at location /opt/julias/julia-1.11/bin will be used.
Loading setup script for JuliaCall...
┌ Error: Error during initialization of module CHOLMOD
│   exception =
│    could not load symbol "SuiteSparse_config_malloc_func_set":
│    /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.5: undefined symbol: SuiteSparse_config_malloc_func_set
│    Stacktrace:
│      [1] __init__()
│        @ SparseArrays.CHOLMOD /opt/julias/julia-1.11/share/julia/stdlib/v1.11/SparseArrays/src/solvers/cholmod.jl:233
│      [2] run_module_init(mod::Module, i::Int64)
│        @ Base ./loading.jl:1378
│      ...
└ @ SparseArrays.CHOLMOD /opt/julias/julia-1.11/share/julia/stdlib/v1.11/SparseArrays/src/solvers/cholmod.jl:250
Finish loading setup script for JuliaCall.
... Validating Julia installation... 
... Setting up Julia project... 
  Activating project at `/home/lavendergroup/wahoo-flapper`
... Handling dependencies... 
... `Julia` set up with 1 thread(s). 
`patter::julia_connect()` call ended @ 2025-06-08 12:43:54 (duration: ~14 sec(s)).
```

</details>
